FROM node:20-bullseye  AS development

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install -f 

# Copy source code
COPY . .

# Expose port
EXPOSE 5005

# Development command (will be overridden by docker-compose)
CMD ["npm", "run", "dev"]
